# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to='posts'),
            preserve_default=False,
        ),
    ]
